ctrl ansible_connection=local
# ctrl ansible_host=192.168.56.100 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/ctrl/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'