apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      name: http
    {{- if .Values.app.metrics.enabled }}
    - port: {{ .Values.app.metrics.port }}
      targetPort: {{ .Values.app.metrics.port }}
      name: metrics
    {{- end }}