{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-{{ .Values.app.name }}
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.model.name }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-{{ .Values.model.name }}
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
{{- if .Values.shadow.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-{{ .Values.model.name }}-shadow
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-{{ .Values.model.name }}-shadow
  subsets:
    - name: shadow
      labels:
        version: shadow
{{- end }}
{{- end }}

