apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.model.name }}
  labels:
    app: {{ .Values.model.name }}
spec:
  selector:
    app: {{ .Values.model.name }}
  ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
      name: http
    {{- if and .Values.model.metrics.enabled (ne .Values.model.metrics.port .Values.model.port) }}
    - port: {{ .Values.model.metrics.port }}
      targetPort: {{ .Values.model.metrics.port }}
      name: metrics
    {{- end }}