{{- if and .Values.istio.enabled .Values.shadow.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-{{ .Values.model.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "{{ .Release.Name }}-{{ .Values.model.name }}"
  http:
    - route:
        - destination:
            host: "{{ .Release.Name }}-{{ .Values.model.name }}"
            port:
              number: {{ .Values.model.port }}
      mirror:
        host: "{{ .Release.Name }}-{{ .Values.model.name }}-shadow"
        port:
          number: {{ .Values.model.port }}
      mirrorPercentage:
        value: {{ .Values.shadow.mirrorPercentage | default 100.0 }}
{{- end }}

