{
 "title": "SMS App Metrics CD",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CANARY Requests per Endpoint (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(index_requests_total{job=\"sms-checker-app-service-canary\"}[1m]))",
     "legendFormat": "index"
    },
    {
     "expr": "sum(rate(predict_requests_total{job=\"sms-checker-app-service-canary\"}[1m]))",
     "legendFormat": "predict"
    }
   ]
  },
  {
   "title": "CANARY Backend Prediction Processing Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(prediction_latency_seconds_sum{job=\"sms-checker-app-service-canary\"}[1m])) / sum(rate(prediction_latency_seconds_count{job=\"sms-checker-app-service-canary\"}[1m]))",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "STABLE Requests per Endpoint (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(index_requests_total{job=\"sms-checker-app-service\"}[1m]))",
     "legendFormat": "index"
    },
    {
     "expr": "sum(rate(predict_requests_total{job=\"sms-checker-app-service\"}[1m]))",
     "legendFormat": "predict"
    }
   ]
  },
  {
   "title": "STABLE Backend Prediction Processing Time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(prediction_latency_seconds_sum{job=\"sms-checker-app-service\"}[1m])) / sum(rate(prediction_latency_seconds_count{job=\"sms-checker-app-service\"}[1m]))",
     "legendFormat": "avg latency"
    }
   ]
  }
 ]
}